settings:
  title: 'Dribdat Status'
  url: 'https://status.dribdat.cc' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: dribdat-opendatach
    name: 'Opendata.ch Hackdays'
    url: 'https://hack.opendata.ch/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true
    
  - id: dribdat-opendatach-energy
    name: 'Energy Data Hackdays'
    url: 'https://hack.energy.opendata.ch/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true
    
  - id: dribdat-opendatach-glam
    name: 'GLAM Hackdays'
    url: 'https://hack.glam.opendata.ch/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true
    
  - id: dribdat-opendatach-showcase
    name: 'Open Data Showcase'
    url: 'https://showcase.opendata.ch/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true
  
  - id: dribdat-hack4socialgood
    name: 'Hack4SocialGood'
    url: 'https://bd.hack4socialgood.ch'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: dribdat-openlegallab
    name: 'Open Legal Lab'
    url: 'https://challenges.openlegallab.ch/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true
    
  - id: dribdat-datahackdays-be
    name: 'Data Hackdays BE'
    url: 'https://hack.data-hackdays-be.ch/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: dribdat-schoolofdata
    name: 'School of Data'
    url: 'https://db.schoolofdata.ch/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true
